### ISSUE TITLE
Support for SFTP Local Users on Storage account

### ISSUE THREAD

**Issue by raswinraaj** [claranet/terraform-azurerm-storage-sftp#1]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for SFTP local users on Storage account is now available in Terraform. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_local_user . 
Can this be added to the module instead of the custom resource "Azapi" using the localusers api at https://github.com/claranet/terraform-azurerm-storage-sftp/blob/master/r-sftp-users.tf? 

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account_local_user

**Comment by zfiel** [comment]
Hello @raswinraaj, thank you for your suggestion, the change will be made as soon as possible.

**Comment by zfiel** [comment]
Hello @raswinraaj , the change has been made (v7.1.0).
